### ISSUE TITLE
'CUDA_ERROR_INVALID_HANDLE' [Op:FloorMod] 

### ISSUE THREAD

**Issue by AlanaRm-rf-me** [AlanaRm-rf-me/Ai-forecast#3]

**Comment by cycle-five** [comment]
Fix for the issue on ubuntu,
```bash
sudo apt update && sudo apt install nvidia-cuda-toolkit && sudo apt autoremove
```

**Comment by AlanaRm-rf-me** [comment]
Note: 
Will add in driver validation, for now the program will default to CPU unless it detects a driver.

**Comment by cycle-five** [comment]
So this is what the issue currently is, still googling
```
error: libdevice not found at ./libdevice.10.bc
```
Did you say there was something with directories that I needed to do?
